addons:
  sonarcloud:
    organization: "vujicgit"
    token:
      secure: "**************************" # encrypted value of your token

script:
  - ./isa/mvnw clean install -DskipTests=false -B
  - ./isa/mvnw sonar:sonar -Dsonar.projectKey=$PROJECT_KEY -Dsonar.organization=vujicgit -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN